const SET_TASK = 'SET_TASK';
const SET_INPUT = 'SET_INPUT';
const VALID_TASK = 'VALID_TASK';
const INVALID_TASK = 'INVALID_TASK';
const RESET_VALIDATION_RESULT = 'RESET_VALIDATION_RESULT';

export default {
    SET_TASK,
    SET_INPUT,
    VALID_TASK,
    INVALID_TASK,
    RESET_VALIDATION_RESULT
};